// seed_real_exam.js — Seeds the Real Exam Walkthrough question bank (template_id 2)
// Run AFTER running 004_real_exam.sql in Supabase
// Run: node db/seed_real_exam.js
require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function seed() {
  // Load the question files generated by agents
  const files = ['real_exam_a.json', 'real_exam_b.json'];
  let allQuestions = [];
  for (const file of files) {
    const filePath = path.join(__dirname, '..', file);
    if (!fs.existsSync(filePath)) {
      console.error(`Missing file: ${filePath}`);
      process.exit(1);
    }
    const batch = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    allQuestions = allQuestions.concat(batch);
  }

  // Ensure all have template_id 2 and required fields are non-null
  const required = ['question_text', 'option_a', 'option_b', 'option_c', 'option_d', 'rationale', 'domain'];
  const before = allQuestions.length;
  allQuestions = allQuestions
    .map(q => ({ ...q, template_id: 2 }))
    .filter(q => required.every(f => q[f] != null && q[f] !== ''));
  const dropped = before - allQuestions.length;
  if (dropped > 0) console.log(`Dropped ${dropped} questions with missing required fields.`);

  console.log(`Seeding ${allQuestions.length} real exam questions...`);

  // Delete existing real exam attempts/answers first
  await supabase.from('attempt_answers')
    .delete().neq('id', '00000000-0000-0000-0000-000000000000');
  await supabase.from('exam_attempts')
    .delete().eq('template_id', 2);
  const { error: delErr } = await supabase.from('questions')
    .delete().eq('template_id', 2);
  if (delErr) { console.error('Delete failed:', delErr); process.exit(1); }
  console.log('Old real exam questions deleted.');

  // Insert in batches of 100
  const BATCH = 100;
  for (let i = 0; i < allQuestions.length; i += BATCH) {
    const batch = allQuestions.slice(i, i + BATCH);
    const { error } = await supabase.from('questions').insert(batch);
    if (error) { console.error(`Insert failed at ${i}:`, error); process.exit(1); }
    console.log(`Inserted ${Math.min(i + BATCH, allQuestions.length)} / ${allQuestions.length}`);
  }

  // Summary
  const domains = {};
  const vignetteCount = allQuestions.filter(q => q.vignette_id).length;
  const standaloneCount = allQuestions.filter(q => !q.vignette_id).length;
  allQuestions.forEach(q => { domains[q.domain] = (domains[q.domain] || 0) + 1; });

  console.log('\nDomain breakdown:');
  Object.entries(domains).forEach(([d, c]) => console.log(`  ${d}: ${c}`));
  console.log(`\nVignette-linked: ${vignetteCount} | Standalone: ${standaloneCount}`);
  console.log('\nReal Exam seeding complete!');
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
